name: CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull From GitHub
        run: git pull jobs master
      - name: Stop Pm2
        run: pm2 stop ecosystem.config.js
      - name: Start Pm2
        run: pm2 stop ecosystem.config.js
      - name: Restart Caddy
        run: sudo systemctl restart caddy
