name: CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop PM2
        run: pm2 delete jobs-api || true
      - name: Delete Existing repo
        run: rm -r Jobs-Api || true
      - name: Clone From GitHub
        run: git clone git@github.com:ruby-tech1/Jobs-Api.git || git clone https://github.com/ruby-tech1/Jobs-Api.git
      - name: Start Pm2
        run: pm2 start ecosystem.config.js || pm2 restart ecosystem.config.js
      - name: Restart Caddy
        run: sudo systemctl restart caddy || echo "Failed to restart Caddy"
