name: CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clone From GitHub
        run: git clone git@github.com:ruby-tech1/Jobs-Api.git
      - name: Stop PM2
        run: pm2 stop ecosystem.config.js
      - name: Start Pm2
        run: pm2 stop ecosystem.config.js
      - name: Restart Caddy
        run: sudo systemctl restart caddy
