name: CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Change Dir To Working
        run: cd Jobs-Api
      - name: Stop PM2
        run: pm2 stop ecosystem.config.js
      - name: Change Dir Back
        run: cd ..
      - name: Delete Existing repo
        run: rm -r Jobs-Api
      - name: Clone From GitHub
        run: git clone git@github.com:ruby-tech1/Jobs-Api.git
      - name: Change Dir To Working
        run: cd Jobs-Api
      - name: Start Pm2
        run: pm2 stop ecosystem.config.js
      - name: Restart Caddy
        run: sudo systemctl restart caddy
