name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull rubytech/aws-test:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f aws-test-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 5000:5000 --env-file=/env/.env --name aws-test-container rubytech/aws-test
