name: CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build -t rubytech/aws-test .
      - name: Push to Dockerhub
        run: docker push rubytech/aws-test:latest
# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed

# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Pull Docker Image
#         run: sudo docker pull rubytech/aws-test:latest
#       - name: Delete Old Docker Container
#         run: sudo docker rm -f aws-test-container || true
#       - name: Run Docker Container
#         run: sudo docker run -d -p 5000:5000 --env-file /home/ubuntu/env/.env --name aws-test-container rubytech/aws-test
