name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.rubytech}}
        DOCKER_PASSWORD: ${{secrets.Starces*?}}
      run: docker login -u $D
    - name: Build the Docker image
      run: docker build -t aws-test
    - name: Push to Dockerhub
      run: docker push rubytech/aws-test:latest
